import { AUTH_CONFIG } from "./auth.config.ts";
import { ENV_CONFIG } from "./env.config.ts";

export const SWAGGER_CONFIG = {
  exposeRoute: true,
  openapi: {
    components: {
      securitySchemes: {
        apiKey: {
          in: "header",
          name: "apiKey",
          type: "apiKey",
        },
        bearerAuthRefresh: {
          bearerFormat: "JWT",
          description: "Refresh Token for obtaining new Access Token",
          in: "header",
          name: AUTH_CONFIG.refreshTokenKey,
          type: "apiKey",
        },
        bearerTokenAuth: {
          bearerFormat: "JWT",
          in: "header",
          name: "Bearer Token",
          scheme: "bearer",
          type: "http",
        },
      },
    },
    consumes: ["application/json"],
    externalDocs: {
      description: "Find more info here",
      url: "https://swagger.io",
    },
    host: new URL(ENV_CONFIG.APPLICATION_URL).host,
    info: {
      description: "Autogenerated API documentation",
      title: "API documentation",
      version: ENV_CONFIG.VERSION || "1.0.0",
    },
    produces: ["application/json"],
  },
  routePrefix: "/docs",
};

export const SWAGGER_UI_CONFIG = {
  routePrefix: "/docs",
  theme: {
    css: [{ filename: "theme.css" }],
  },
  uiConfig: {
    deepLinking: true,
    defaultModelsExpandDepth: 3,
    defaultModelExpandDepth: 3,
    displayRequestDuration: true,
    docExpansion: "list" as const,
    filter: true,
    operationsSorter: "alpha" as const,
    persistAuthorization: true,
    requestSnippetsEnabled: true,
    requestSnippets: {
      generators: {
        curl_bash: { title: "cURL (bash)", syntax: "bash" },
        curl_powershell: { title: "cURL (PowerShell)", syntax: "powershell" },
      },
      defaultExpanded: false,
      languages: null,
    },
    syntaxHighlight: { theme: "monokai" as const },
    tagsSorter: "alpha" as const,
    tryItOutEnabled: true,
  },
};

/** @deprecated use SWAGGER_CONFIG and SWAGGER_UI_CONFIG separately */
export const OPENAPI_CONFIG = SWAGGER_CONFIG;
